---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 이미지를 넣어주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_2715e9beac3b
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              value: jdbc:mysql://mysql:3306/krampoline
            - name: REDIS_SERVICE
              value: redis-service
            - name: ALLOWED_ORIGIN
              value: "*"
            - name: REDIRECT_URL
              value: https://k56b28d9d3ecca.user-app.krampoline.com/
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: kakao_client_id
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: kakao_client_secret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: google_client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: google_client_secret
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_password
          resources:
            requests:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
