apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "my-secret-pw"
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mariadb-storage
  volumes:
  - name: mariadb-storage
    persistentVolumeClaim:
      claimName: mariadb-pvc
