---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: krmp-d2hub-idock.9rum.cc/dev-test/repo_cf9b9e0e64bf
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: db_password
        - name: MARIADB_DATABASE
          value: krampoline
        - name: MARIADB_DISABLE_UPGRADE_BACKUP
          value: '1'
        - name: TZ
          value: Asia/Seoul
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
        readinessProbe:
          tcpSocket:
            port: 3306
      volumes:
      - name: init-db
        configMap:
          name: init-db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mariadb
